language: java
jdk:
- oraclejdk8
script: mvn clean package
addons:
  artifacts: true
deploy:
  provider: releases
  api_key:
    secure: x3v8C7UhaoNgcwIJOdkoFCqbunQdKw5UnzC4t5CC31YsgCQoGwWoWJfNj6cMidZiFzmj66/9QtZEjR4fFJ+DSYcS3ZCsBZTt3sUF2WmjBzX20o170IITfgB9x24ii6XLZuPTji4Tj9El3iwtYWi8EjamO/xpSC9gSWoOp+N1EjAlqlIH9YookQRv83AnoaHwwYvzYHco0xHlxv7HDj2sWY0NmH4eNfdN4bDZNcn9Ga3vcG4Xz1kGKIH7BBPJ3LV9KsKSbALoSx1guqqgQxCf3W4WLBWuX/ozMiObqo0NePc1oW3vmfixtmVsRkFD/x9fTFj+vQ3Ej290PeSBM9gPmvck6pjW+mXirKjL31LRWM3iG/vyW6HFqRi4BTtrpN9HuLSKsOCK0jinqKbXnmA5w6fQ9WRgqJx1VGZ/0NH8GDQTEcKqF7GAsx8ZsrE3oSnQOjxQifnNvj90hpg2bOob159ZftDhNZvMBpn+q7vhqB3eH/rN11QC5vTKusvZXw6ZF0XSvckZalifBIgIPhu/MLO3lYCUkl0TF3jJWqVpdbadAjkyBZwFFb1dG2j6ZOUYGAL44vjtBoenBcqHehM3zeiZN+aHPxF4kytQJp/zJ7i3f/kkW6P/jACMa2mdDR8Aj/wBdE6U1YerNDzqESbxDk9d8CC4bolrAZvPFTCMJQM=
  file: target/*.jar
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
    
