language: java
jdk:
- oraclejdk8
script: mvn clean package
addons:
  artifacts: true
deploy:
  provider: releases
  api_key:
    secure: QP1c4n+q8DIebi8DNAxFFplkv/xqNot2tsSiwQbN/tWke98JuDCcrBIKJvDS31pxbUjiCODf8pA7LqW3ndPFKuFKFb+cVkloDF8TpXVbfvqsnYH7MxoL02mUNxYnN63U7lN/Jaj3qam6hP3pVMhLQedCOGmoaJxhugN9r/ZvXMs26K6mPj3Eot/D00Q5mwMV7S9ZIl1oN2CDCDUHXhOY8e2V3EkIE/Dv4Z3VbmKjXYChTwHrLAb/FmpGSr1tgdu8rP6kK0elLxG2fupKy7gSZjCBo96O0XakhPNoNWx18631/RLUwPR/n+YS90TJO3dX5UT2tR7zhNH3KNkMH53elyYVV5nT1PQJBeTwInyJtDEuwGNlnrjLKCAXTfh70UBFzG/yBpPlKZOqj7wpfKOvozLqcZ48+Gz56+i9udX+eDi7xvvK4CfRp3/ZPduBldw7BZZpYnuTo2GcNAaNhV1K2M1CElEiu/afXCh9aW+YQN6MPAS9PWWoo+b4m8yqVP1XRc0/CA/n++jl7WCyAZVDgT7pDDWfDzzQvWD7XXVCQkytArbXff4UJyPt7F/nUHrDs11zndxbE3iMpghYjC/D9ERAKajHxIeZ9aZ6JU1XgxTodLt0c56QijGJC00obyO6xWQfDB1AXJnYzwid0vAuMrYSSlTLLCm4szLzHSvOZQU=
  file: target/*.jar
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
